<?php
session_start();
unset($_SESSION["id"]);
unset($_SESSION["fname"]);
unset($_SESSION["lname"]);
unset($_SESSION["email"]);
unset($_SESSION["age"]);
unset($_SESSION["password"]);
unset($_SESSION["status"]);
header('refresh:1;url=../vaccine/index.php?page=Login');
?>